### ISSUE TITLE
Size limitation 

### ISSUE THREAD

**Issue by pranathivemuri** [cwood1967/napari-nikon-nd2#1]
HI! Thanks for this repo - probably not an issue with your plugin but  I was wondering if you observed any size limitation while using this plugin for your files. I have a nd2 file that is about 6 gb with 2048x2048x150 and has 5 channels. My computer has 32 GB RAM, but it doesn't seem to be enough. The same file opens well in imagej though but the volume can't be rendered in imagej with the same out of memory error

Would you have any recommendations for visualizing such big volumes? Thanks in advance! :)

**Comment by cwood1967** [comment]
Hi. This is probably the result of (me) converting the data to 32-bit while reading the image. I will try to update this.

Otherwise, there is also this plugin that can read nd2 (and other) image files:
https://github.com/AllenCellModeling/napari-aicsimageio

that can read nd2 images and probably has better features.

~Chris

**Comment by pranathivemuri** [comment]
thanks @cwood1967 makes sense, napari-aicsimageio worked with the same nd2 file
